TOKEN = "t.V4QVXUA5khrTJcMQNsCCDC3IfD94uJA5Yj_FpR8UfaMs3KxSY0tlIlSDe3ix6G7CcKYMbfQTNlLSWR2l1aHQjQ" 
ACTIONS_MAIN = {
    'DOWNLOAD_FUNDAMENTALS_DATA': 1,
    'DOWNLOAD_TICKERS': 2,
    'DOWNLOAD_DATA_HISTORICAL_PRICES_SHARES': 3,
    'DOWNLOAD_DATA_COMMODITIES': 4,
    'CLUSTER_ANALYSIS': 5,
    'TREE_SOLVE_ANALYSIS': 6,
    'CAPM': 7,
    'CAPM_FF': 8,
    'MULTIPLICATOR_P_E': 9,
    'MULTIPLICATOR_P_BV': 10,
    'MULTIPLICATOR_P_S': 11,
    'MULTIPLICATOR_EV_EBITDA': 12,
    'MULTIPLICATOR_PEG': 13,
    'ANALYSIS_NN': 14,
    'EXIT': 0
}

ACTIONS_DOWNLOAD = {
    'DOWNLOAD_ONE_SHARE_QUOTES': 1,
    'DONWLOAD_MANY_SHARE_QUOTES': 2
}