ACTIONS_MAIN = {
    "DOWNLOAD_DATA": 1,
    "FULL_ANALYSIS": 2,
    "REGRESSION_ANALYSIS": 3,
    "CLUSTER_ANALYSIS": 4,
    "TREE_SOLVER_ANALYSIS": 5,
    "RISK_AI_ANALYSIS": 6,
    "EXIT": 0,
}

ACTIONS_DOWNLOAD = {"DOWNLOAD_ONE_SHARE_QUOTES": 1, "DONWLOAD_MANY_SHARE_QUOTES": 2}
