TOKEN = "t.V4QVXUA5khrTJcMQNsCCDC3IfD94uJA5Yj_FpR8UfaMs3KxSY0tlIlSDe3ix6G7CcKYMbfQTNlLSWR2l1aHQjQ"
TOKEN_SECOND = "t.skzwvKDie7H0cSN-caMPUsgWALKvrwJQLbJvcvXrifFpcvG4H5yX3ofzHBwvFyT7QeXhwyzPAJr71NLmRMYmRA"
ACTIONS_MAIN = {
    "FULL_ANALYSIS": 1,
    "DOWNLOAD_DATA": 2,
    "EXIT": 0,
}

ACTIONS_DOWNLOAD = {"DOWNLOAD_ONE_SHARE_QUOTES": 1, "DONWLOAD_MANY_SHARE_QUOTES": 2}
